# Generated by Django 2.2.1 on 2019-08-05 13:44

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmeta',
            name='icon',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Icon', to='filer.File'),
        ),
    ]
