# Generated by Django 2.2.1 on 2019-08-05 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0002_lessonmeta_icon'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonmetadata',
            unique_together={('description', 'lesson')},
        ),
    ]
