# Generated by Django 2.2.1 on 2019-08-08 13:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0003_auto_20190805_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedbacklesson',
            new_name='lesson',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.Course'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='gender_female',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)], verbose_name='Weiblich'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='gender_male',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)], verbose_name='Männlich'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='gender_other',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)], verbose_name='Anderes Geschlecht'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='negative',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)], verbose_name='Negativ'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='positive',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)], verbose_name='Positiv'),
        ),
    ]
