# Generated by Django 2.2.1 on 2019-08-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0004_auto_20190808_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='gender_female',
            new_name='female',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='gender_male',
            new_name='male',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='gender_other',
            new_name='other',
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('course', 'lesson')},
        ),
    ]
