# Generated by Django 2.2.1 on 2019-08-08 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0005_auto_20190808_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum'),
        ),
    ]
