# Generated by Django 2.2.1 on 2019-08-08 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0006_auto_20190808_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='female',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)], verbose_name='Weiblich'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='male',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)], verbose_name='Männlich'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='negative',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)], verbose_name='Rote Bälle'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='other',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)], verbose_name='Anderes Geschlecht'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='positive',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)], verbose_name='Grüne Bälle'),
        ),
    ]
