# Generated by Django 2.2.1 on 2019-08-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0009_news_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='added_by',
            new_name='author',
        ),
    ]
