# Generated by Django 2.2.1 on 2019-08-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0010_auto_20190821_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Veröffentlichungsdatum'),
        ),
    ]
