# Generated by Django 2.2.1 on 2020-03-10 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0012_course_timeframe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Lektionsanhang', 'verbose_name_plural': 'Lektionsanhänge'},
        ),
        migrations.AlterModelOptions(
            name='courselesson',
            options={'verbose_name': 'Zuordnung Kurs-Lektion', 'verbose_name_plural': 'Zuordnungen Kurs-Lektion'},
        ),
        migrations.AlterModelOptions(
            name='courseuser',
            options={'verbose_name': 'Zuordnung Kurs-Benutzer', 'verbose_name_plural': 'Zuordnungen Kurs-Benutzer'},
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Partnerlogo', 'verbose_name_plural': 'Partnerlogos'},
        ),
        migrations.AddField(
            model_name='news',
            name='menu_item',
            field=models.BooleanField(blank=True, null=True, verbose_name='Hauptmenü'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='attached_file',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attached_file', to='filer.File', verbose_name='Datei'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.Lesson', verbose_name='Lektion'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.Course', verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.Lesson', verbose_name='Lektion'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.Course', verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.Course', verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.Lesson', verbose_name='Lektion'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='gui.Lesson', verbose_name='Übergeordnete Lektion'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.TextField(max_length=500, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='lessonmeta',
            name='icon',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icon', to='filer.File', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='lessonmetadata',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.LessonMeta', verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='lessonmetadata',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.Lesson', verbose_name='Lektion'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
