# Generated by Django 3.2.6 on 2021-08-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0015_auto_20210826_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='quote_child',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Zitat eines Kindes'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Kommentar des Coaches'),
        ),
    ]
