# Generated by Django 3.2.6 on 2021-09-21 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0016_auto_20210826_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='negative',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)], verbose_name='Negativ'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='positive',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)], verbose_name='Positiv'),
        ),
        migrations.AlterField(
            model_name='lessonmetadata',
            name='value',
            field=models.TextField(max_length=150, verbose_name='Text'),
        ),
    ]
