# Generated by Django 3.2.7 on 2021-09-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0017_auto_20210921_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Tag (Datum)')),
                ('school', models.TextField(max_length=500, verbose_name='Schule')),
                ('course', models.TextField(max_length=500, verbose_name='Klasse')),
                ('location', models.TextField(max_length=500, verbose_name='Ort')),
                ('rate', models.DecimalField(decimal_places=0, max_digits=40, verbose_name='Stundensatz / Honorar')),
            ],
            options={
                'verbose_name': 'Abrechnung',
                'verbose_name_plural': 'Abrechnungen',
            },
        ),
    ]
