# Generated by Django 3.2.7 on 2021-09-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0018_deduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=40, verbose_name='Stundensatz / Honorar'),
        ),
    ]
