# Generated by Django 3.2.6 on 2021-09-21 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0018_alter_attachment_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='description',
            new_name='title',
        ),
    ]
