# Generated by Django 3.2.7 on 2021-09-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0019_alter_deduction_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='day',
            field=models.DateTimeField(verbose_name='Tag (Datum)'),
        ),
    ]
