# Generated by Django 3.2.6 on 2021-10-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0019_rename_description_attachment_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonmetadata',
            options={'ordering': ['sort'], 'verbose_name': 'Lektionsmetainformation', 'verbose_name_plural': 'Lektionsmetainformationen'},
        ),
        migrations.AddField(
            model_name='lessonmetadata',
            name='sort',
            field=models.IntegerField(default=-1, max_length=150, verbose_name='Sortierung'),
        ),
    ]
