# Generated by Django 3.2.7 on 2021-09-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0020_alter_deduction_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='day',
            field=models.DateField(verbose_name='Tag (Datum)'),
        ),
    ]
