# Generated by Django 3.2.6 on 2021-10-28 11:36

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0012_file_mime_type'),
        ('gui', '0021_auto_20211021_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Titel')),
                ('content', models.TextField(blank=True, verbose_name='Inhalt')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='gui.knowledgearticle', verbose_name='Übergeordneter Artikel')),
            ],
            options={
                'verbose_name': 'Wissen-Artikel',
                'verbose_name_plural': 'Wissen-Artikel',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titel')),
                ('attached_file', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_file', to='filer.file', verbose_name='Datei')),
                ('knowledge_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='gui.knowledgearticle', verbose_name='Wissen-Artikel')),
            ],
            options={
                'verbose_name': 'Wissens-Artikel-Anhang',
                'verbose_name_plural': 'Wissens-Artikel-Anhänge',
            },
        ),
    ]
