# Generated by Django 3.2.14 on 2022-07-27 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gui', '0022_knowledgearticle_knowledgeattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(verbose_name='Stundensatz')),
            ],
            options={
                'verbose_name': 'Stundensatz',
                'verbose_name_plural': 'Stundensätze',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Startdatum Übungsleitervertrag'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='gui.course', verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='courseuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
        migrations.AlterField(
            model_name='lessonmetadata',
            name='sort',
            field=models.IntegerField(default=-1, verbose_name='Sortierung'),
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField(verbose_name='Stunden')),
                ('date', models.DateField(verbose_name='Tag')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.course', verbose_name='Kurs')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kursleiter*in')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.hourlyrate', verbose_name='Stundensatz')),
            ],
            options={
                'verbose_name': 'Stundenerfassung',
                'verbose_name_plural': 'Stundenerfassung',
            },
        ),
    ]
