# Generated by Django 4.2.2 on 2023-07-11 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gui", "0025_auto_20220803_0838"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="childprotection",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="end_blue",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="end_green",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="end_red",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="end_yellow",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="female",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="male",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="other",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="start_blue",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="start_green",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="start_red",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="start_yellow",
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="rate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gui.hourlyrate",
                verbose_name="Vergütung",
            ),
        ),
    ]
